[REVIEW] Проверка дали броя на скобите е достатъчен
triffon/sdp-2024-25 pull request #6
Opened 2024-10-19 13:24 UTC by dimoyordanov

2024-10-23 05:37 UTC, triffon requested changes
Опитай се да направиш проверката за коректност на скоби по време на пресмятане на израза, вместо да дублираш обхожданото със стек.

2024-10-24 04:49 UTC, dimoyordanov commented
Fixed.

2024-10-24 07:57 UTC, triffon requested changes
Сега вече като проверката е заедно с пресмятането, не ти трябва отделен стек за скобите, можеш да използваш стека с операции.

2024-10-26 12:50 UTC, dimoyordanov commented
Оправено.

2024-11-04 07:18 UTC, triffon requested changes
Предложих леко подобрение

2024-11-04 07:18 UTC, triffon commented on lectures/calculator/rpn_calculator.cpp
> +            if(ops.empty())
Тази проверка се дублира. Може да се сложи в условието на цикъла и да се провери един път след цикъла, а не в началото и всеки път в тялото.

2025-01-18 15:42 UTC, closed without merging